Document: scribe-server-orig
Title: Debian scribe-server-orig Manual
Author: <insert document author here>
Abstract: This manual describes what scribe-server-orig is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/scribe-server-orig/scribe-server-orig.sgml.gz

Format: postscript
Files: /usr/share/doc/scribe-server-orig/scribe-server-orig.ps.gz

Format: text
Files: /usr/share/doc/scribe-server-orig/scribe-server-orig.text.gz

Format: HTML
Index: /usr/share/doc/scribe-server-orig/html/index.html
Files: /usr/share/doc/scribe-server-orig/html/*.html
